<?php
/**
 * Story Graph relationship management.
 *
 * @package StoryOS
 */

namespace StoryOS\Utils;

/**
 * Relationship types defined by the Story Graph.
 *
 * @return array
 */
function relationship_types(): array {
	return [
		'contains'        => 'Contains - Parent-child ownership',
		'appears_in'      => 'Appears In - Narrative participation',
		'located_in'      => 'Located In - Geographic placement',
		'references'      => 'References - Associative link',
		'derived_from'    => 'Derived From - Provenance tracking',
		'related_to'      => 'Related To - General relationship',
		'belongs_to'      => 'Belongs To - Ownership',
		'linked_to'       => 'Linked To - General association',
		'used_in'         => 'Used In - Usage relationship',
		'generated_by'    => 'Generated By - Origin tracking',
	];
}

/**
 * Add a relationship between two Story Graph entities.
 *
 * @param int    $from_id    The source entity ID.
 * @param string $from_type  The source CPT slug.
 * @param int    $to_id      The target entity ID.
 * @param string $to_type    The target CPT slug.
 * @param string $type       The relationship type.
 * @param array  $metadata   Additional relationship metadata.
 * @return int|WP_Error The relationship ID or error.
 */
function add_relationship( int $from_id, string $from_type, int $to_id, string $to_type, string $type = 'references', array $metadata = [] ) {
	// Validate entity types.
	$valid_types = array_keys( storyos_get_all_cpts() );
	if ( ! in_array( $from_type, $valid_types, true ) || ! in_array( $to_type, $valid_types, true ) ) {
		return new \WP_Error( 'invalid_entity_type', 'Invalid entity type.' );
	}

	// Validate relationship type.
	$valid_relations = array_keys( relationship_types() );
	if ( ! in_array( $type, $valid_relations, true ) ) {
		return new \WP_Error( 'invalid_relationship_type', 'Invalid relationship type.' );
	}

	// Store relationship in post meta.
	$meta_key = STORYOS_CPT_PREFIX . 'relationships';
	$existing = get_post_meta( $from_id, $meta_key, true );

	if ( ! is_array( $existing ) ) {
		$existing = [];
	}

	$relationship = [
		'to_id'      => $to_id,
		'to_type'    => $to_type,
		'type'       => $type,
		'metadata'   => $metadata,
		'created'    => current_time( 'mysql' ),
	];

	$existing[] = $relationship;
	update_post_meta( $from_id, $meta_key, $existing );

	storyos_log( "Relationship added: {$from_type}({$from_id}) -> {$type} -> {$to_type}({$to_id})" );

	return count( $existing );
}

/**
 * Replace a scalar relationship slot with one current target.
 *
 * StoryOS fields such as Sound -> Scene are scalar selectors. Re-saving one of
 * those fields must replace its old edge rather than append duplicate or stale
 * relationships. The field name in metadata identifies the slot.
 *
 * @param int    $from_id   Source entity ID.
 * @param string $from_type Source CPT slug.
 * @param int    $to_id     Target entity ID, or zero to clear the slot.
 * @param string $to_type   Target CPT slug.
 * @param string $type      Relationship type.
 * @param array  $metadata  Relationship metadata. The `field` key is recommended.
 * @return int|\WP_Error Relationship count, zero when cleared, or an error.
 */
function set_relationship( int $from_id, string $from_type, int $to_id, string $to_type, string $type = 'references', array $metadata = [] ) {
	$valid_types = array_keys( storyos_get_all_cpts() );
	if ( ! in_array( $from_type, $valid_types, true ) || ! in_array( $to_type, $valid_types, true ) ) {
		return new \WP_Error( 'invalid_entity_type', 'Invalid entity type.' );
	}

	if ( ! isset( relationship_types()[ $type ] ) ) {
		return new \WP_Error( 'invalid_relationship_type', 'Invalid relationship type.' );
	}

	$meta_key   = STORYOS_CPT_PREFIX . 'relationships';
	$existing   = get_post_meta( $from_id, $meta_key, true );
	$existing   = is_array( $existing ) ? $existing : [];
	$field_name = sanitize_key( (string) ( $metadata['field'] ?? '' ) );

	$existing = array_values(
		array_filter(
			$existing,
			static function( array $relationship ) use ( $to_type, $type, $field_name ): bool {
				if ( $to_type !== (string) ( $relationship['to_type'] ?? '' ) || $type !== (string) ( $relationship['type'] ?? '' ) ) {
					return true;
				}

				if ( '' === $field_name ) {
					return false;
				}

				$existing_field = sanitize_key( (string) ( $relationship['metadata']['field'] ?? '' ) );
				return '' !== $existing_field && $field_name !== $existing_field;
			}
		)
	);

	update_post_meta( $from_id, $meta_key, $existing );

	if ( 0 === $to_id ) {
		return 0;
	}

	$metadata['field'] = $field_name;
	return add_relationship( $from_id, $from_type, $to_id, $to_type, $type, $metadata );
}

/**
 * Get all relationships for an entity.
 *
 * @param int    $entity_id The entity ID.
 * @param string $entity_type The entity CPT slug.
 * @param string $direction The direction: 'outgoing' or 'incoming'.
 * @return array
 */
function get_relationships( int $entity_id, string $entity_type = '', string $direction = 'outgoing' ): array {
	$relationships = [];

	if ( 'outgoing' === $direction ) {
		$meta_key = STORYOS_CPT_PREFIX . 'relationships';
		$rels = get_post_meta( $entity_id, $meta_key, true );

		if ( is_array( $rels ) ) {
			foreach ( $rels as $rel ) {
				$rel['from_id'] = $entity_id;
				$rel['from_type'] = $entity_type;
				$relationships[] = $rel;
			}
		}
	} else {
		// Incoming: search all entities for relationships pointing to this one.
		$all_cpts = storyos_get_all_cpts();
		foreach ( $all_cpts as $cpt => $label ) {
			$posts = get_posts( [
				'post_type'      => $cpt,
				'post_status'    => 'any',
				'posts_per_page' => -1,
				'meta_query'     => [
					[
						'key'     => STORYOS_CPT_PREFIX . 'relationships',
						'compare' => 'EXISTS',
					],
				],
			] );

			foreach ( $posts as $post ) {
				$rels = get_post_meta( $post->ID, STORYOS_CPT_PREFIX . 'relationships', true );
				if ( is_array( $rels ) ) {
					foreach ( $rels as $rel ) {
						if ( (int) ( $rel['to_id'] ?? 0 ) === $entity_id && (string) ( $rel['to_type'] ?? '' ) === $entity_type ) {
							$rel['from_id'] = $post->ID;
							$rel['from_type'] = $cpt;
							$relationships[] = $rel;
						}
					}
				}
			}
		}
	}

	return $relationships;
}

/**
 * Remove a relationship.
 *
 * @param int    $from_id   The source entity ID.
 * @param int    $to_id     The target entity ID.
 * @param string $from_type The source CPT slug.
 * @param string $to_type   The target CPT slug.
 * @return bool
 */
function remove_relationship( int $from_id, int $to_id, string $from_type = '', string $to_type = '' ): bool {
	$meta_key = STORYOS_CPT_PREFIX . 'relationships';
	$rels = get_post_meta( $from_id, $meta_key, true );

	if ( ! is_array( $rels ) ) {
		return false;
	}

	$original_count = count( $rels );
	$rels = array_values( array_filter( $rels, function( $rel ) use ( $to_id, $to_type ) {
		return !( $rel['to_id'] === $to_id && ( ! $to_type || $rel['to_type'] === $to_type ) );
	} ) );

	$removed = $original_count !== count( $rels );
	if ( $removed ) {
		update_post_meta( $from_id, $meta_key, $rels );
		storyos_log( "Relationship removed: {$from_type}({$from_id}) -> {$to_type}({$to_id})" );
	}

	return $removed;
}

/**
 * Get related entities for a given entity, traversing the graph.
 *
 * @param int    $entity_id The entity ID.
 * @param string $entity_type The entity CPT slug.
 * @param int    $depth     How many levels to traverse.
 * @return array
 */
function get_graph_entities( int $entity_id, string $entity_type = '', int $depth = 1 ): array {
	$visited = [];
	$queue = [ [ 'id' => $entity_id, 'type' => $entity_type, 'depth' => 0 ] ];

	$result = [];

	while ( ! empty( $queue ) && $depth >= 0 ) {
		$current = array_shift( $queue );

		if ( $current['depth'] > $depth ) {
			continue;
		}

		$key = $current['type'] . '_' . $current['id'];
		if ( isset( $visited[ $key ] ) ) {
			continue;
		}

		$visited[ $key ] = true;

		$post = get_post( $current['id'] );
		if ( ! $post ) {
			continue;
		}

		$result[ $key ] = [
			'id'    => $post->ID,
			'type'  => $post->post_type,
			'title' => $post->post_title,
			'status'=> $post->post_status,
		];

		// Get outgoing relationships.
		$rels = get_relationships( $current['id'], $current['type'], 'outgoing' );
		foreach ( $rels as $rel ) {
			$queue[] = [
				'id'    => $rel['to_id'],
				'type'  => $rel['to_type'],
				'depth' => $current['depth'] + 1,
				'rel'   => $rel,
			];
		}

		// Traverse incoming relationships too so parent graphs include child-owned
		// entities such as Sound cues that belong to a Scene or Shot.
		$incoming = get_relationships( $current['id'], $current['type'], 'incoming' );
		foreach ( $incoming as $rel ) {
			$queue[] = [
				'id'    => $rel['from_id'],
				'type'  => $rel['from_type'],
				'depth' => $current['depth'] + 1,
				'rel'   => $rel,
			];
		}
	}

	return $result;
}

/**
 * Query the graph for entities matching criteria.
 *
 * @param array $query The query parameters.
 * @return array
 */
function graph_query( array $query = [] ): array {
	$defaults = [
		'entity_type' => '',
		'type'        => '',
		'depth'       => 1,
		'status'      => 'publish',
		'limit'       => 50,
		'offset'      => 0,
	];

	$args = wp_parse_args( $query, $defaults );

	// If entity_type is specified, do a direct query.
	if ( ! empty( $args['entity_type'] ) ) {
		$cpts = storyos_get_all_cpts();
		if ( ! isset( $cpts[ $args['entity_type'] ] ) ) {
			return [];
		}

		$posts = get_posts( [
			'post_type'      => $args['entity_type'],
			'post_status'    => $args['status'],
			'posts_per_page' => $args['limit'],
			'offset'         => $args['offset'],
		] );

		$results = [];
		foreach ( $posts as $post ) {
			$key = $post->post_type . '_' . $post->ID;
			$results[ $key ] = [
				'id'    => $post->ID,
				'type'  => $post->post_type,
				'title' => $post->post_title,
				'status'=> $post->post_status,
			];
		}

		return $results;
	}

	// Otherwise, traverse from a starting point.
	$start_id = $args['start_id'] ?? 0;
	$start_type = $args['start_type'] ?? '';

	if ( ! $start_id || ! $start_type ) {
		return [];
	}

	return get_graph_entities( $start_id, $start_type, $args['depth'] );
}
