<?php
/**
 * Story Graph relationship management.
 *
 * @package StoryOS
 */

namespace StoryOS\Utils;

/**
 * Relationship types defined by the Story Graph.
 *
 * @return array
 */
function relationship_types(): array {
	return [
		'contains'        => 'Contains - Parent-child ownership',
		'appears_in'      => 'Appears In - Narrative participation',
		'located_in'      => 'Located In - Geographic placement',
		'references'      => 'References - Associative link',
		'derived_from'    => 'Derived From - Provenance tracking',
		'related_to'      => 'Related To - General relationship',
		'belongs_to'      => 'Belongs To - Ownership',
		'linked_to'       => 'Linked To - General association',
		'used_in'         => 'Used In - Usage relationship',
		'generated_by'    => 'Generated By - Origin tracking',
	];
}

/**
 * Get the private marker used to distinguish a cleared graph field from
 * unmigrated named relationship meta.
 *
 * @param string $field_name Relationship field name.
 * @return string
 */
function relationship_field_marker_key( string $field_name ): string {
	return '_storyos_relationship_field_' . sanitize_key( $field_name );
}

/**
 * Add a relationship between two Story Graph entities.
 *
 * @param int    $from_id    The source entity ID.
 * @param string $from_type  The source CPT slug.
 * @param int    $to_id      The target entity ID.
 * @param string $to_type    The target CPT slug.
 * @param string $type       The relationship type.
 * @param array  $metadata   Additional relationship metadata.
 * @return int|WP_Error The relationship ID or error.
 */
function add_relationship( int $from_id, string $from_type, int $to_id, string $to_type, string $type = 'references', array $metadata = [] ) {
	// Validate entity types.
	$valid_types = array_keys( storyos_get_all_cpts() );
	if ( ! in_array( $from_type, $valid_types, true ) || ! in_array( $to_type, $valid_types, true ) ) {
		return new \WP_Error( 'invalid_entity_type', 'Invalid entity type.' );
	}

	$entities_valid = validate_relationship_entities( $from_id, $from_type, $to_id, $to_type );
	if ( is_wp_error( $entities_valid ) ) {
		return $entities_valid;
	}

	// Validate relationship type.
	$valid_relations = array_keys( relationship_types() );
	if ( ! in_array( $type, $valid_relations, true ) ) {
		return new \WP_Error( 'invalid_relationship_type', 'Invalid relationship type.' );
	}

	// Store relationship in post meta.
	$meta_key = STORYOS_CPT_PREFIX . 'relationships';
	$existing = get_post_meta( $from_id, $meta_key, true );

	if ( ! is_array( $existing ) ) {
		$existing = [];
	}

	foreach ( $existing as $relationship ) {
		if (
			$to_id === (int) ( $relationship['to_id'] ?? 0 ) &&
			$to_type === (string) ( $relationship['to_type'] ?? '' ) &&
			$type === (string) ( $relationship['type'] ?? '' ) &&
			$metadata === (array) ( $relationship['metadata'] ?? [] )
		) {
			return count( $existing );
		}
	}

	$relationship = [
		'to_id'      => $to_id,
		'to_type'    => $to_type,
		'type'       => $type,
		'metadata'   => $metadata,
		'created'    => current_time( 'mysql' ),
	];

	$existing[] = $relationship;
	update_post_meta( $from_id, $meta_key, $existing );

	storyos_log( "Relationship added: {$from_type}({$from_id}) -> {$type} -> {$to_type}({$to_id})" );

	return count( $existing );
}

/**
 * Replace a scalar relationship slot with one current target.
 *
 * StoryOS fields such as Sound -> Scene are scalar selectors. Re-saving one of
 * those fields must replace its old edge rather than append duplicate or stale
 * relationships. The field name in metadata identifies the slot.
 *
 * @param int    $from_id   Source entity ID.
 * @param string $from_type Source CPT slug.
 * @param int    $to_id     Target entity ID, or zero to clear the slot.
 * @param string $to_type   Target CPT slug.
 * @param string $type      Relationship type.
 * @param array  $metadata  Relationship metadata. The `field` key is recommended.
 * @return int|\WP_Error Relationship count, zero when cleared, or an error.
 */
function set_relationship( int $from_id, string $from_type, int $to_id, string $to_type, string $type = 'references', array $metadata = [] ) {
	$valid_types = array_keys( storyos_get_all_cpts() );
	if ( ! in_array( $from_type, $valid_types, true ) || ! in_array( $to_type, $valid_types, true ) ) {
		return new \WP_Error( 'invalid_entity_type', 'Invalid entity type.' );
	}

	$entities_valid = validate_relationship_entities( $from_id, $from_type, $to_id, $to_type, true );
	if ( is_wp_error( $entities_valid ) ) {
		return $entities_valid;
	}

	if ( ! isset( relationship_types()[ $type ] ) ) {
		return new \WP_Error( 'invalid_relationship_type', 'Invalid relationship type.' );
	}

	$meta_key   = STORYOS_CPT_PREFIX . 'relationships';
	$existing   = get_post_meta( $from_id, $meta_key, true );
	$existing   = is_array( $existing ) ? $existing : [];
	$field_name = sanitize_key( (string) ( $metadata['field'] ?? '' ) );

	$existing = array_values(
		array_filter(
			$existing,
			static function( array $relationship ) use ( $to_type, $type, $field_name ): bool {
				if ( $to_type !== (string) ( $relationship['to_type'] ?? '' ) || $type !== (string) ( $relationship['type'] ?? '' ) ) {
					return true;
				}

				if ( '' === $field_name ) {
					return false;
				}

				$existing_field = sanitize_key( (string) ( $relationship['metadata']['field'] ?? '' ) );
				return '' !== $existing_field && $field_name !== $existing_field;
			}
		)
	);

	update_post_meta( $from_id, $meta_key, $existing );

	if ( 0 === $to_id ) {
		if ( '' !== $field_name ) {
			update_post_meta( $from_id, relationship_field_marker_key( $field_name ), 1 );
		}
		return 0;
	}

	$metadata['field'] = $field_name;
	$result = add_relationship( $from_id, $from_type, $to_id, $to_type, $type, $metadata );
	if ( ! is_wp_error( $result ) && '' !== $field_name ) {
		update_post_meta( $from_id, relationship_field_marker_key( $field_name ), 1 );
	}

	return $result;
}

/**
 * Replace all targets assigned to one SCF relationship field.
 *
 * SCF's Relationship field can store more than one post, while
 * set_relationship() intentionally models a scalar slot. This helper keeps a
 * multi-value SCF control and the canonical Story Graph in sync without
 * allowing stale edges to accumulate.
 *
 * @param int               $from_id    Source post ID.
 * @param string            $from_type  Source CPT.
 * @param array<int, mixed> $target_ids Target post IDs.
 * @param string            $to_type    Target CPT.
 * @param string            $type       Relationship verb.
 * @param string            $field_name SCF field name.
 * @return int|\WP_Error Relationship count, or a validation error.
 */
function set_relationships_for_field( int $from_id, string $from_type, array $target_ids, string $to_type, string $type, string $field_name ) {
	$valid_types = array_keys( storyos_get_all_cpts() );
	if ( ! in_array( $from_type, $valid_types, true ) || ! in_array( $to_type, $valid_types, true ) ) {
		return new \WP_Error( 'invalid_entity_type', 'Invalid entity type.' );
	}

	if ( $from_id <= 0 || $from_type !== get_post_type( $from_id ) ) {
		return new \WP_Error( 'invalid_source_entity', 'The relationship source does not match its declared entity type.' );
	}

	if ( ! isset( relationship_types()[ $type ] ) ) {
		return new \WP_Error( 'invalid_relationship_type', 'Invalid relationship type.' );
	}

	$target_ids = array_values( array_unique( array_filter( array_map( 'absint', $target_ids ) ) ) );
	foreach ( $target_ids as $target_id ) {
		$valid = validate_relationship_entities( $from_id, $from_type, $target_id, $to_type );
		if ( is_wp_error( $valid ) ) {
			return $valid;
		}
	}

	$field_name = sanitize_key( $field_name );
	$meta_key   = STORYOS_CPT_PREFIX . 'relationships';
	$existing   = get_post_meta( $from_id, $meta_key, true );
	$existing   = is_array( $existing ) ? $existing : [];
	$existing   = array_values(
		array_filter(
			$existing,
			static function( array $relationship ) use ( $to_type, $type, $field_name ): bool {
				$existing_field = sanitize_key( (string) ( $relationship['metadata']['field'] ?? '' ) );
				if ( '' !== $existing_field ) {
					return $field_name !== $existing_field;
				}

				// Legacy edges did not identify their source control. Remove only
				// those that match this field's configured target and verb.
				return $to_type !== (string) ( $relationship['to_type'] ?? '' ) || $type !== (string) ( $relationship['type'] ?? '' );
			}
		)
	);
	update_post_meta( $from_id, $meta_key, $existing );

	foreach ( $target_ids as $target_id ) {
		$result = add_relationship(
			$from_id,
			$from_type,
			$target_id,
			$to_type,
			$type,
			[ 'field' => $field_name ]
		);
		if ( is_wp_error( $result ) ) {
			return $result;
		}
	}

	update_post_meta( $from_id, relationship_field_marker_key( $field_name ), 1 );

	return count( $target_ids );
}

/**
 * Validate that relationship IDs resolve to the declared StoryOS CPTs.
 *
 * @param int    $from_id    Source post ID.
 * @param string $from_type  Declared source CPT.
 * @param int    $to_id      Target post ID.
 * @param string $to_type    Declared target CPT.
 * @param bool   $allow_zero Whether a zero target is a scalar-slot clear.
 * @return true|\WP_Error
 */
function validate_relationship_entities( int $from_id, string $from_type, int $to_id, string $to_type, bool $allow_zero = false ) {
	if ( $from_id <= 0 || $from_type !== get_post_type( $from_id ) ) {
		return new \WP_Error( 'invalid_source_entity', 'The relationship source does not match its declared entity type.' );
	}

	if ( 0 === $to_id && $allow_zero ) {
		return true;
	}

	if ( $to_id <= 0 || $to_type !== get_post_type( $to_id ) ) {
		return new \WP_Error( 'invalid_target_entity', 'The relationship target does not match its declared entity type.' );
	}

	return true;
}

/**
 * Get all relationships for an entity.
 *
 * @param int    $entity_id The entity ID.
 * @param string $entity_type The entity CPT slug.
 * @param string $direction The direction: 'outgoing' or 'incoming'.
 * @return array
 */
function get_relationships( int $entity_id, string $entity_type = '', string $direction = 'outgoing' ): array {
	$relationships = [];

	if ( 'outgoing' === $direction ) {
		$meta_key = STORYOS_CPT_PREFIX . 'relationships';
		$rels = get_post_meta( $entity_id, $meta_key, true );

		if ( is_array( $rels ) ) {
			foreach ( $rels as $rel ) {
				$rel['from_id'] = $entity_id;
				$rel['from_type'] = $entity_type;
				$relationships[] = $rel;
			}
		}
	} else {
		// Incoming: search all entities for relationships pointing to this one.
		$all_cpts = storyos_get_all_cpts();
		foreach ( $all_cpts as $cpt => $label ) {
			$posts = get_posts( [
				'post_type'      => $cpt,
				'post_status'    => 'any',
				'posts_per_page' => -1,
				'meta_query'     => [
					[
						'key'     => STORYOS_CPT_PREFIX . 'relationships',
						'compare' => 'EXISTS',
					],
				],
			] );

			foreach ( $posts as $post ) {
				$rels = get_post_meta( $post->ID, STORYOS_CPT_PREFIX . 'relationships', true );
				if ( is_array( $rels ) ) {
					foreach ( $rels as $rel ) {
						if ( (int) ( $rel['to_id'] ?? 0 ) === $entity_id && (string) ( $rel['to_type'] ?? '' ) === $entity_type ) {
							$rel['from_id'] = $post->ID;
							$rel['from_type'] = $cpt;
							$relationships[] = $rel;
						}
					}
				}
			}
		}
	}

	return $relationships;
}

/**
 * Remove a relationship.
 *
 * @param int    $from_id   The source entity ID.
 * @param int    $to_id     The target entity ID.
 * @param string $from_type The source CPT slug.
 * @param string $to_type   The target CPT slug.
 * @return bool
 */
function remove_relationship( int $from_id, int $to_id, string $from_type = '', string $to_type = '' ): bool {
	$meta_key = STORYOS_CPT_PREFIX . 'relationships';
	$rels = get_post_meta( $from_id, $meta_key, true );

	if ( ! is_array( $rels ) ) {
		return false;
	}

	$original_count = count( $rels );
	$rels = array_values( array_filter( $rels, function( $rel ) use ( $to_id, $to_type ) {
		return !( $rel['to_id'] === $to_id && ( ! $to_type || $rel['to_type'] === $to_type ) );
	} ) );

	$removed = $original_count !== count( $rels );
	if ( $removed ) {
		update_post_meta( $from_id, $meta_key, $rels );
		storyos_log( "Relationship removed: {$from_type}({$from_id}) -> {$to_type}({$to_id})" );
	}

	return $removed;
}

/**
 * Remove every incoming Story Graph edge before a StoryOS post is deleted.
 *
 * @param int $post_id Post being deleted.
 */
function cleanup_relationships_for_deleted_post( int $post_id ): void {
	$post_type = get_post_type( $post_id );
	if ( ! $post_type || ! isset( storyos_get_all_cpts()[ $post_type ] ) ) {
		return;
	}

	$meta_key = STORYOS_CPT_PREFIX . 'relationships';
	foreach ( array_keys( storyos_get_all_cpts() ) as $cpt ) {
		$posts = get_posts(
			[
				'post_type'      => $cpt,
				'post_status'    => 'any',
				'posts_per_page' => -1,
				'fields'         => 'ids',
				'meta_query'     => [
					[
						'key'     => $meta_key,
						'compare' => 'EXISTS',
					],
				],
			]
		);

		foreach ( $posts as $source_id ) {
			if ( $post_id === (int) $source_id ) {
				continue;
			}

			$relationships = get_post_meta( $source_id, $meta_key, true );
			if ( ! is_array( $relationships ) ) {
				continue;
			}

			$remaining = array_values(
				array_filter(
					$relationships,
					static function( array $relationship ) use ( $post_id, $post_type ): bool {
						return $post_id !== (int) ( $relationship['to_id'] ?? 0 ) || $post_type !== (string) ( $relationship['to_type'] ?? '' );
					}
				)
			);

			if ( count( $remaining ) !== count( $relationships ) ) {
				if ( empty( $remaining ) ) {
					delete_post_meta( $source_id, $meta_key );
				} else {
					update_post_meta( $source_id, $meta_key, $remaining );
				}
			}
		}
	}
}

/**
 * Get related entities for a given entity, traversing the graph.
 *
 * @param int    $entity_id The entity ID.
 * @param string $entity_type The entity CPT slug.
 * @param int    $depth     How many levels to traverse.
 * @return array
 */
function get_graph_entities( int $entity_id, string $entity_type = '', int $depth = 1 ): array {
	$visited = [];
	$queue = [ [ 'id' => $entity_id, 'type' => $entity_type, 'depth' => 0 ] ];

	$result = [];

	while ( ! empty( $queue ) && $depth >= 0 ) {
		$current = array_shift( $queue );

		if ( $current['depth'] > $depth ) {
			continue;
		}

		$key = $current['type'] . '_' . $current['id'];
		if ( isset( $visited[ $key ] ) ) {
			continue;
		}

		$visited[ $key ] = true;

		$post = get_post( $current['id'] );
		if ( ! $post ) {
			continue;
		}

		$result[ $key ] = [
			'id'    => $post->ID,
			'type'  => $post->post_type,
			'title' => $post->post_title,
			'status'=> $post->post_status,
		];

		if ( $current['depth'] >= $depth ) {
			continue;
		}

		// Get outgoing relationships.
		$rels = get_relationships( $current['id'], $current['type'], 'outgoing' );
		foreach ( $rels as $rel ) {
			$queue[] = [
				'id'    => $rel['to_id'],
				'type'  => $rel['to_type'],
				'depth' => $current['depth'] + 1,
				'rel'   => $rel,
			];
		}

		// Traverse incoming relationships too so parent graphs include child-owned
		// entities such as Sound cues that belong to a Scene or Shot.
		$incoming = get_relationships( $current['id'], $current['type'], 'incoming' );
		foreach ( $incoming as $rel ) {
			$queue[] = [
				'id'    => $rel['from_id'],
				'type'  => $rel['from_type'],
				'depth' => $current['depth'] + 1,
				'rel'   => $rel,
			];
		}
	}

	return $result;
}

/**
 * Query the graph for entities matching criteria.
 *
 * @param array $query The query parameters.
 * @return array
 */
function graph_query( array $query = [] ): array {
	$defaults = [
		'entity_type' => '',
		'type'        => '',
		'depth'       => 1,
		'status'      => 'publish',
		'limit'       => 50,
		'offset'      => 0,
	];

	$args = wp_parse_args( $query, $defaults );

	// If entity_type is specified, do a direct query.
	if ( ! empty( $args['entity_type'] ) ) {
		$cpts = storyos_get_all_cpts();
		if ( ! isset( $cpts[ $args['entity_type'] ] ) ) {
			return [];
		}

		$posts = get_posts( [
			'post_type'      => $args['entity_type'],
			'post_status'    => $args['status'],
			'posts_per_page' => $args['limit'],
			'offset'         => $args['offset'],
		] );

		$results = [];
		foreach ( $posts as $post ) {
			$key = $post->post_type . '_' . $post->ID;
			$results[ $key ] = [
				'id'    => $post->ID,
				'type'  => $post->post_type,
				'title' => $post->post_title,
				'status'=> $post->post_status,
			];
		}

		return $results;
	}

	// Otherwise, traverse from a starting point.
	$start_id = $args['start_id'] ?? 0;
	$start_type = $args['start_type'] ?? '';

	if ( ! $start_id || ! $start_type ) {
		return [];
	}

	return get_graph_entities( $start_id, $start_type, $args['depth'] );
}
